UPCourt.Web/Controllers/CaseStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class CaseStatusController : BaseMVCController
    {
        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanView)]
        // GET: CaseStatus
        public ActionResult Index()
        {
            return View(CaseStatusMvcModel.CopyFromEntityList(CaseStatusDataService.GetLite(db).OrderByDescending(i => i.DisplayOrder), 0));
        }

        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanView)]
        // GET: CaseStatus/Details/5
        public ActionResult Details(Guid id)
        {
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == id).FirstOrDefault();
            if (dbData == null)
            {
                return RedirectToAction("Index");
            }
            return View(CaseStatusMvcModel.CopyFromEntity(dbData, 0));
        }

        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanCreate)]
        // GET: CaseStatus/Create
        public ActionResult Create()
        {
            var model = new CaseStatusMvcModel();
            return View(model);
        }
        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanCreate)]
        [HttpPost]
        public ActionResult Create(CaseStatusMvcModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            if (!CommonForInsertUpdate(model)) { return View(model); }

            CaseStatus tempCaseStatus = new CaseStatus();
            tempCaseStatus.CaseStatusId = Guid.NewGuid();
            InitializeData(tempCaseStatus, model);

            tempCaseStatus.ModifiedBy = AppUser.UserId;
            tempCaseStatus.ModifiedOn = DateTime.Now;

            db.CaseStatuses.Add(tempCaseStatus);
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, CreatedMessage);
            return RedirectToAction("Index");
        }


        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanEdit)]
        // GET: CaseStatus/Edit/5
        public ActionResult Edit(Guid id)
        {
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == id).FirstOrDefault();
            if (dbData == null) { return RedirectToAction("Index"); }
            return View(CaseStatusMvcModel.CopyFromEntity(dbData, 0));
        }

        // POST: CaseStatus/Edit/5
        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanEdit)]
        [HttpPost]
        public ActionResult Edit(CaseStatusMvcModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == model.CaseStatusId).FirstOrDefault();
            if (dbData == null) { return RedirectToAction("Index"); }
            if (!CommonForInsertUpdate(model)) { return View(model); }
            InitializeData(dbData, model);
            dbData.ModifiedBy = AppUser.UserId;
            dbData.ModifiedOn = DateTime.Now;
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, UpdatedMessage);
            return RedirectToAction("Index");
        }
        [PageRoleAuthorizarion(PageName.CaseStatus, PagePermissionType.CanDelete)]
        public ActionResult Delete(Guid id)
        {
            var dbData = CaseStatusDataService.GetLite(db).Where(i => i.CaseStatusId == id).FirstOrDefault();
            dbData.IsDeleted = true;
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, DeletedMessage);
            return RedirectToAction("Index");
        }
        private void InitializeData(CaseStatus tempCaseStatus, CaseStatusMvcModel model)
        {
            tempCaseStatus.Name = model.Name;
            tempCaseStatus.HexColorCode = model.HexColorCode;
        }
        private bool CommonForInsertUpdate(CaseStatusMvcModel model)
        {
            var nameForCheck = model.Name.TrimX();
            var duplicateCheck = CaseStatusDataService.GetLite(db).FirstOrDefault(i => i.CaseStatusId != model.CaseStatusId && i.Name == nameForCheck);
            if (duplicateCheck != null)
            {
                ModelState.AddModelError(nameof(model.Name), "Case Status name already exists");
                return false;
            }
            var ClourCodeForCheck = model.HexColorCode.TrimX();
            var duplicateCheckColour = CaseStatusDataService.GetLite(db).FirstOrDefault(i => i.CaseStatusId != model.CaseStatusId && i.HexColorCode == ClourCodeForCheck);

            if (duplicateCheckColour != null)
            {
                ModelState.AddModelError(nameof(model.HexColorCode), "Case color code already exists");
                return false;
            }
            return true;
        }
    }
}

UPCourt.Web/Views/CaseStatus/Create.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Add Case-Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "CaseStatus", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.CaseStatusId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Case-Status</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })    <span class="text-danger">*</span>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "txtCase", @maxlength = "75", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group my-colorpicker2">
                            @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-square"></i></span>
                            </div>
                            @Html.ValidationMessageFor(model => model.HexColorCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="@Url.Action("Index", "CaseStatus")" class="btn btn-primary">
                    Back
                </a>
                &nbsp;
                <button type="submit" class="btn btn-primary" onclick="return validateData();">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}
<script>

    function validateData() {

        if ($("#txtCase").val() != "") {
            var txtvalue = $("#txtCase").val();
            if (isValid(txtvalue)) {
                return true;
            }
            else {
                ToastError("Special character are not allowed .");
                return false;
            }
        }
    }
    function isValid(str) {
        return /^[a-zA-Z0-9- ]*$/.test(str);
    }
</script>

UPCourt.Web/Views/CaseStatus/Details.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Case Status Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case Status Details</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case Status Details</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Case Status</h3>
    </div>
    <form>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @readonly = "readonly" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text", @readonly = "readonly" } })

                </div>
            </div>
        
        </div>
        <div class="card-footer">
            <a href="@Url.Action("Index", "CaseStatus")" class="btn btn-primary">
                Back
            </a>
        </div>

    </form>
</div>
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/CaseStatus/Edit.cshtml
@model UPCourt.Web.Models.CaseStatusMvcModel

@{
    ViewBag.Title = "Edit Case Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "CaseStatus", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.CaseStatusId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Case Status</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })     <span class="text-danger">*</span>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "txtCase", @maxlength = "75", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
              
                <div class="row">
                    <div class="form-group col-md-12">
                        @Html.LabelFor(model => model.HexColorCode, htmlAttributes: new { @class = "control-label" })
                        <div class="input-group my-colorpicker2">
                            @Html.EditorFor(model => model.HexColorCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @required = "true" } })
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-square"></i></span>
                            </div>
                        </div>
                        @Html.ValidationMessageFor(model => model.HexColorCode, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary" onclick="return validateData();">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}


<script>

    function validateData() {
       
        if ($("#txtCase").val() != "") {
            var txtvalue = $("#txtCase").val();
            if (isValid(txtvalue)) {
                return true;
            }
            else {
                ToastError("Special character are not allowed .");
                return false;
            }
        }
    }
    function isValid(str) {
        return /^[a-zA-Z0-9- ]*$/.test(str);
    }
</script>

UPCourt.Web/Views/CaseStatus/Index.cshtml
@model IEnumerable<UPCourt.Web.Models.CaseStatusMvcModel>

@{
    ViewBag.Title = "Case Status List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Case Status</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Case Status</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title float-right">
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Hex Color Code</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="tr-class-2">
                                <td>@item.Name</td>
                                <td style="background-color:@item.HexColorCode;">@item.HexColorCode</td>

                                <td class="project-actions">
                                    <a class="" title="View" href="@Url.Action("Details", "CaseStatus", new { id = item.CaseStatusId })">
                                        <i class="fa fa-eye text-warning fa-iconsize"></i>
                                    </a>
                                    &nbsp;
                                    <a class="" title="Edit" href="@Url.Action("Edit", "CaseStatus", new { id = item.CaseStatusId })">
                                        <i class="fa fa-edit text-info fa-iconsize mr-2 "></i>
                                    </a>
                                    &nbsp;
                                    <a title="Delete" onclick="ConfirmDelete('@item.CaseStatusId','@item.Name','CaseStatus')">
                                        <i class="fa fa-trash-alt text-danger fa-iconsize mr-2 "></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/datatables/CustomDataTable.js")
}