UPCourt.Web/Controllers/LawOfficerController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class LawOfficerController : BaseMVCController
    {
        // GET: LawOfficer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(StateLawOfficer model)
        {
            StateLawOfficer tempData = new StateLawOfficer
            {
                AdvId = Guid.NewGuid(),
                AdvName = model.AdvName,
                AdvEnrl = model.AdvEnrl,
                AdvAor = model.AdvAor,
                AdvLocation = model.AdvLocation,
                AdvPost = model.AdvPost,
                CreatedOn = DateTime.Now,
                CreatedBy = AppUser.UserId,
            };
            db.StateLawOfficer.Add(tempData);
            db.SaveChangesWithAudit(Request, "");
            SucessMessage = $"DC Govt. Department {tempData.AdvName} Created successfully";
            ViewBag.Msg = SucessMessage;
            DisplayMessage(MessageType.Success, SucessMessage);
            return RedirectToAction("Create");

        }
        public ActionResult List()
        {
            StateLawOfficerIndexMvcModel model = new StateLawOfficerIndexMvcModel() { };

            var dbData = StateLawOfficerDataService.GetDetail(db).Where(F => F.AdvPost == "A.A.G").OrderByDescending(i => i.AdvName).ToList();
            model.StateLawOfficersDocs = StateLawOfficerModel.CopyFromEntityList(dbData, 0);

            var dbDataa = StateLawOfficerDataService.GetDetail(db).Where(F => F.AdvPost == "G.A").OrderByDescending(i => i.AdvName).ToList();
            model.StateLawOfficersDocsGA = StateLawOfficerModel.CopyFromEntityList(dbDataa, 0);

            var dbDataaa = StateLawOfficerDataService.GetDetail(db).Where(F => F.AdvPost == "CSE" || F.AdvPost== "CSE-I" || F.AdvPost== "CSE-II" || F.AdvPost== "CSE-V").OrderByDescending(i => i.AdvName).ToList();
            model.StateLawOfficersDocsCSE = StateLawOfficerModel.CopyFromEntityList(dbDataaa, 0);
            var dbDataaaa = StateLawOfficerDataService.GetDetail(db).Where(F => F.AdvPost == "A.CSE").OrderByDescending(i => i.AdvName).ToList();
            model.StateLawOfficersDocsACSE = StateLawOfficerModel.CopyFromEntityList(dbDataaaa, 0);

            return View(model);
        }

        [HttpGet]
        public ActionResult GetList(string d)
        {
            var dbData = StateLawOfficerDataService.GetLite(db).Where(i => i.AdvPost == "A.A.G").ToList();
            return Json(JsonConvert.SerializeObject(dbData), JsonRequestBehavior.AllowGet);
        }
    }
}

UPCourt.Web/Views/LawOfficer/Create.cshtml
@model UPCourt.Web.Models.StateLawOfficerModel
@using UPCourt.Entity
@{
    ViewBag.Title = "Add State Law Officer";

    Layout = "~/Views/Shared/_OuterLayout.cshtml";
}
@section Scripts {
    <script src="~/Scripts/GovermentDepartment/GovermentDepartment.js"></script>
    <script>
        var Msg = '@ViewBag.Msg';

        if (Msg != undefined && Msg != null && Msg != "") {
            alert(Msg);
        }
    </script>

}
<div class="container">


    @using (Html.BeginForm("Create", "LawOfficer", FormMethod.Post, new { @class = "" }))
    {
        @Html.HiddenFor(model => model.AdvId)

        <div class="breadcrumbnew">
            <a class="active" href="@Url.Action("Index", "Home")">Home</a> <i class="fa fa-angle-right"></i> <a href="#">Government Department</a>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card my-4">
                    <div class="card-header no-bg">
                        <h3 class="f-20 my-1">Add State Law Officer</h3>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="form-group tabforminner col-md-6">
                                @Html.LabelFor(model => model.AdvName, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.AdvName, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })

                               
                            </div>

                            <div class="form-group tabforminner col-md-6">
                                @Html.LabelFor(model => model.AdvPost, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.AdvPost, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                              </div>

                            <div class="form-group tabforminner col-md-4">
                                @Html.LabelFor(model => model.AdvLocation, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.AdvLocation, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                             
                            </div>
                            <div class="form-group tabforminner col-md-4">
                                @Html.LabelFor(model => model.AdvEnrl, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.AdvEnrl, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                                 </div>

                            <div class="form-group tabforminner col-md-4">
                                @Html.LabelFor(model => model.AdvAor, htmlAttributes: new { @class = "form-check-label" })<span class="text-danger">*</span>
                                @Html.EditorFor(model => model.AdvAor, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                                
                            </div>

                        </div>




                        <button type="submit"
                                data-callback='onSubmit' data-action='submit' class="btn btn-warning displaybtn mt-4" onclick="confirmrregister()">
                            Submit
                        </button>

                    </div>


                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <script>
                       
                        function validatePhoneNo(Phone) {
                            var re = /^\+?[0-9-]+$/;
                            return re.test(Phone);
                        }
                        function AddGDDCContact() {
                            debugger;
                            var max = 1000;
                            var rowCount = $('.GDDCContact').length;
                            var LastRowCount = rowCount - 1;
                            if (LastRowCount <= max) {
                                var newCounselorRow = $('#GDDCContact_' + LastRowCount).clone();

                                newCounselorRow.find("checkbox, select, textarea, input, span, label, a").each(function () {
                                    if ($(this).attr("id") != undefined)
                                        $(this).attr("id", $(this).attr("id").replace(LastRowCount, rowCount));
                                    if ($(this).attr("name") != undefined)
                                        $(this).attr("name", $(this).attr("name").replace(LastRowCount, rowCount));
                                    if ($(this).attr("data-valmsg-for") != undefined)
                                        $(this).attr("data-valmsg-for", $(this).attr("data-valmsg-for").replace(LastRowCount, rowCount));
                                    if ($(this).attr("for") != undefined)
                                        $(this).attr("for", $(this).attr("for").replace(LastRowCount, rowCount));
                                });

                                //Update seq no.
                                newCounselorRow.find('td:eq(0)').text(rowCount + 1);

                                newCounselorRow.find("select, textarea, input").each(function () {
                                    $(this).attr("value", "");
                                });
                                newCounselorRow.find(".IsFirstRow").css("display", "none");
                                newCounselorRow.find(".Removebtn").css("display", "block");
                                newCounselorRow.find(".addNewbtn").css("display", "none");
                                newCounselorRow.find(".NewId").val('');

                                $('#divDepartmentContacts').append("<tr id=\"GDDCContact_" + rowCount + "\" class=\"GDDCContact\">" + newCounselorRow.html() + "</tr>");
                                setSerialNos();
                            }
                        }

                        function checkSelected(obj) {
                            if ($(obj).val() == "Others") {
                                $("#dvOtherDistrict").css('display', '');
                                $("#OtherDistrict").attr("required", "true");
                            }
                            else {
                                $("#dvOtherDistrict").css('display', 'none');
                                $("#OtherDistrict").removeAttr("required");
                            }
                        }
                        function RemoveAddedItem(btn) {
                            var id = $(btn).attr('id');
                            $('#' + id.replace('Remove', '')).hide();
                            $('#' + id.replace('Remove', '')).find("[id$=bActive]").val("false");
                            setSerialNos();
                            $('#' + id.replace('Remove', '') + ' input').each(function () {
                                $(this).removeAttr("required");
                            });
                        }
                        
                        function checkChange(obj) {
                            var found = false;
                            $("#District option").each(function () {
                                if (found) return;
                                if ($(this).val().toLowerCase() === $(obj).val().toLowerCase()) {
                                    $("#District").val($(this).val());
                                    $(obj).val('');
                                    $(obj).css('display', 'none');
                                    $(obj).removeAttr("required");
                                    found = true;
                                }
                                else if ($(obj).is(':visible')) {
                                    $('#District').val("Others");
                                    $(obj).css('display', '');
                                    $(obj).attr("required", "true");
                                }
                            });
                        }
                    
                        function confirmrregister() {
                            alert("Do You Want Save The Data");
                        }



                    </script>

                </div>
            </div>
        </div>



    }

</div>