UPCourt.Web/Controllers/HolidayGovController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class HolidayGovController : BaseMVCController
    {
        private CustomUserManager CustomUserManager { get; set; }
        public HolidayGovController() : this(new CustomUserManager())
        {
        }
        public HolidayGovController(CustomUserManager customUserManager)
        {
            CustomUserManager = customUserManager;
        }
        // GET: HolidayGov
        public ActionResult Index()
        {
            var dbData = HolidayListDataService.GetLite(db).ToList();
            return View(HolidayMvcModel.CopyFromEntityList(dbData, 0));
        }
        public ActionResult Create()
        {
            Initilizeholiday(null);
            InitilizHStatus(null);
            return View();
        }
        [HttpPost]
        public ActionResult Create(HolidayMvcModel model)
        {
            // Code for validating the CAPTCHA
            InitilizHStatus(model.HolidayName);
            Holiday tempData = new Holiday
            {
                HolidayId = Guid.NewGuid(),
                HolidayName = model.HolidayName,
                Hdate = model.Hdate,
                Hyear = model.Hyear,
                CreatedOn = DateTime.Now,
                CreatedBy = AppUser.UserId,
                HStatus = model.HStatus,
            };
            db.Holiday.Add(tempData);
            db.SaveChangesWithAudit(Request, "");
            SucessMessage = $"DC Govt. Department {tempData.HolidayName} Created successfully";
            ViewBag.Msg = SucessMessage;
            DisplayMessage(MessageType.Success, SucessMessage);
            return RedirectToAction("Create");

        }

        public ActionResult List()
        {
            InitilizHStatus(null);
            HolidayIndexMvcModel model = new HolidayIndexMvcModel() { };

            var dbData = HolidayListDataService.GetDetail(db).Where(F => F.CreatedBy == AppUser.UserId).OrderByDescending(i => i.HStatus).ToList();
            model.HolidayDocs = HolidayMvcModel.CopyFromEntityList(dbData, 0);

            return View(model);
        }

        [HttpGet]
        public ActionResult GetList(string d)
        {
            var dbData = HolidayListDataService.GetLite(db).Where(i => i.HStatus == d).ToList();
            return Json(JsonConvert.SerializeObject(dbData), JsonRequestBehavior.AllowGet);
        }
        private bool CommonForInsertUpdate(HolidayMvcModel model)
        {
            return true;
        }

        private void InitilizeDistricts(object selectedValue)
        {
            var dbData = DistrictDataService.GetLite(db).OrderBy(i => i.DistrictName).ToList();
            var mvc = DistrictMvcModel.CopyFromEntityList(dbData, 0);
            mvc.Add(new DistrictMvcModel() { DistrictName = "Others" });
            var districts = new SelectList(mvc, nameof(DistrictMvcModel.DistrictName)
                , nameof(DistrictMvcModel.DistrictName), selectedValue);
            ViewBag.Districts = districts;
        }

        private void Initilizeholiday(object selectedValue)
        {
            var dbData = HolidayListDataService.GetLite(db).OrderBy(i => i.HolidayName).ToList();
            var mvc = HolidayMvcModel.CopyFromEntityList(dbData, 0);
            ViewBag.HolidayList = new SelectList(mvc, nameof(HolidayMvcModel.HolidayName)
                , nameof(HolidayMvcModel.HolidayName), selectedValue);
        }
        private void InitilizHStatus(object selectedValue)
        {
            var dbData = HStatusDataService.GetLite(db).OrderBy(i => i.HStatusName).ToList();
            var mvc = HStatusMvcModel.CopyFromEntityList(dbData, 0);
            ViewBag.HStatus = new SelectList(mvc, nameof(HStatusMvcModel.HStatusName)
                , nameof(HStatusMvcModel.HStatusName), selectedValue);
        }
    }
}

UPCourt.Web/Views/HolidayGov/Create.cshtml
@model UPCourt.Web.Models.HolidayMvcModel
@using UPCourt.Entity
@{
    ViewBag.Title = "Add Holiday";

    Layout = "~/Views/Shared/_OuterLayout.cshtml";
}
@section Scripts {
    <script src="~/Scripts/GovermentDepartment/GovermentDepartment.js"></script>
    <script>
        var Msg = '@ViewBag.Msg';

        if (Msg != undefined && Msg != null && Msg != "") {
            alert(Msg);
        }
    </script>

}
<div class="container">


    @using (Html.BeginForm("Create", "HolidayGov", FormMethod.Post, new { @class = "" }))
    {
        @Html.HiddenFor(model => model.HolidayId)

        <div class="breadcrumbnew">
            <a class="active" href="@Url.Action("Index", "Home")">Home</a> <i class="fa fa-angle-right"></i> <a href="#">Government Department</a>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card my-4">
                    <div class="card-header no-bg">
                        <h3 class="f-20 my-1">Add Holiday Name</h3>
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="form-group tabforminner col-md-3">
                                @Html.LabelFor(model => model.HStatus, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.DropDownListFor(m => m.HStatus, ViewBag.HStatus as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control f-14 select2", @style = "width: 100%", @onchange = "checkSelected(this);" })
                                @Html.ValidationMessageFor(model => model.HStatus, "", new { @class = "text-danger" })


                            </div>

                            <div class="form-group tabforminner col-md-6">
                                @Html.LabelFor(model => model.HolidayName, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.HolidayName, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                                  </div>

                            <div class="form-group tabforminner col-md-3">
                                @Html.LabelFor(model => model.HolidayName, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.DropDownListFor(m => m.HolidayName, ViewBag.HolidayList as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control f-14 select2", @style = "width: 100%", @onchange = "checkSelected(this);" })
                                @Html.ValidationMessageFor(model => model.HolidayName, "", new { @class = "text-danger" })


                            </div>
                            <div class="form-group tabforminner col-md-6">
                                @Html.LabelFor(model => model.Hyear, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.EditorFor(model => model.Hyear, new { htmlAttributes = new { @class = "form-control f-14", @maxlength = "100" } })
                                 </div>

                            <div class="col-md-4 form-group">
                                @Html.LabelFor(model => model.Hdate, htmlAttributes: new { @class = "form-check-label" })<span class="text-danger">*</span>
                                @Html.EditorFor(model => model.Hdate, new { htmlAttributes = new { @class = "form-control required", @placeholder = "Enter Receipt No.", @type = "date", @required = "true" } })
                                @Html.ValidationMessageFor(model => model.Hdate, "", new { @class = "text-danger" })
                            </div>

                        </div>
                       



                        <button type="submit"
                                
                                data-callback='onSubmit' data-action='submit' class="btn btn-warning displaybtn mt-4" onclick="confirmrregister()">
                            Submit
                        </button>

                    </div>


                    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                    <script>
                        function validatePhoneNo(Phone) {
                            var re = /^\+?[0-9-]+$/;
                            return re.test(Phone);
                        }
                        function AddGDDCContact() {
                            debugger;
                            var max = 1000;
                            var rowCount = $('.GDDCContact').length;
                            var LastRowCount = rowCount - 1;
                            if (LastRowCount <= max) {
                                var newCounselorRow = $('#GDDCContact_' + LastRowCount).clone();

                                newCounselorRow.find("checkbox, select, textarea, input, span, label, a").each(function () {
                                    if ($(this).attr("id") != undefined)
                                        $(this).attr("id", $(this).attr("id").replace(LastRowCount, rowCount));
                                    if ($(this).attr("name") != undefined)
                                        $(this).attr("name", $(this).attr("name").replace(LastRowCount, rowCount));
                                    if ($(this).attr("data-valmsg-for") != undefined)
                                        $(this).attr("data-valmsg-for", $(this).attr("data-valmsg-for").replace(LastRowCount, rowCount));
                                    if ($(this).attr("for") != undefined)
                                        $(this).attr("for", $(this).attr("for").replace(LastRowCount, rowCount));
                                });

                                //Update seq no.
                                newCounselorRow.find('td:eq(0)').text(rowCount + 1);

                                newCounselorRow.find("select, textarea, input").each(function () {
                                    $(this).attr("value", "");
                                });
                                newCounselorRow.find(".IsFirstRow").css("display", "none");
                                newCounselorRow.find(".Removebtn").css("display", "block");
                                newCounselorRow.find(".addNewbtn").css("display", "none");
                                newCounselorRow.find(".NewId").val('');

                                $('#divDepartmentContacts').append("<tr id=\"GDDCContact_" + rowCount + "\" class=\"GDDCContact\">" + newCounselorRow.html() + "</tr>");
                                setSerialNos();
                            }
                        }

                        function checkSelected(obj) {
                            if ($(obj).val() == "Others") {
                                $("#dvOtherDistrict").css('display', '');
                                $("#OtherDistrict").attr("required", "true");
                            }
                            else {
                                $("#dvOtherDistrict").css('display', 'none');
                                $("#OtherDistrict").removeAttr("required");
                            }
                        }
                        function RemoveAddedItem(btn) {
                            var id = $(btn).attr('id');
                            $('#' + id.replace('Remove', '')).hide();
                            $('#' + id.replace('Remove', '')).find("[id$=bActive]").val("false");
                            setSerialNos();
                            $('#' + id.replace('Remove', '') + ' input').each(function () {
                                $(this).removeAttr("required");
                            });
                        }


                        function checkChange(obj) {
                            var found = false;
                            $("#District option").each(function () {
                                if (found) return;
                                if ($(this).val().toLowerCase() === $(obj).val().toLowerCase()) {
                                    $("#District").val($(this).val());
                                    $(obj).val('');
                                    $(obj).css('display', 'none');
                                    $(obj).removeAttr("required");
                                    found = true;
                                }
                                else if ($(obj).is(':visible')) {
                                    $('#District').val("Others");
                                    $(obj).css('display', '');
                                    $(obj).attr("required", "true");
                                }
                            });
                        }
                        
                        function confirmrregister() {
                            alert("Do You Want Save The Data");
                        }
                    </script>
                </div>
            </div>
        </div>



    }

</div>

UPCourt.Web/Views/HolidayGov/List.cshtml
@model UPCourt.Web.Models.HolidayIndexMvcModel
@using UPCourt.Web.Core;

@{
    int holidayCounter = 0;
    ViewBag.Title = "Holiday List";
}


<style>
    .input-error {
        border-color: #dc3545;
        padding-right: 2.25rem;
    }

    .red {
        color: #dc3545;
    }

    .select2-selection__choice {
        background-color: #b200ff !important;
    }
</style>

<!-- /.content-header -->
<!-- Main content -->
<div class="content">


    <section class="content-fluid">
        <div class="content">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-default">
                        <div class="card-header">
                            <h3 class="card-title">
                                <i class="fas fa-file-alt"></i>
                                Case List
                                <h3 class="card-title float-right">
                                    @Html.ActionLink("Create", "Index", "HolidayGov", null, htmlAttributes: new { @class = "btn btn-primary" })
                                </h3>
                            </h3>
                        </div>

                        <!-- /.card-header -->
                        <div class="card-body">

                            <div class="form-group tabforminner col-md-3">
                                @Html.LabelFor(model => model.HStatus, htmlAttributes: new { @class = "text-black" })<span class="text-danger"> </span>
                                @Html.DropDownListFor(m => m.HStatus, ViewBag.HStatus as IEnumerable<SelectListItem>, "--Select--", new { @class = "form-control f-14 select2", @style = "width: 100%", @onchange = "GetList(this);" })
                                @Html.ValidationMessageFor(model => model.HStatus, "", new { @class = "text-danger" })


                            </div>

                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Holiday Name</th>
                                        <th>Holiday Date</th>
                                        <th>Year</th>
                                        <th>Holiday Type</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var Holiday in Model.HolidayDocs)
                                    {
                                        holidayCounter++;
                                        <tr class="tr-class-2">
                                            <td>@holidayCounter</td>
                                            <td>@Holiday.HolidayName</td>
                                            <td>@Holiday.Hdate</td>
                                            <td>@Holiday.Hyear</td>
                                            <td>@Holiday.HStatus</td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>


        </div>
    </section>

</div>
<!-- /.content -->


@section Scripts {


    <script src="~/FrontEnd/plugins/bs-stepper/js/bs-stepper.min.js"></script>
    <script src="~/Scripts/Court/CommonNotice.js"></script>

    <script src="~/Scripts/Court/noticedelete.js"></script>

}
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');

    });


</script>