UPCourt.Web/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UPCourt.Entity;
using UPCourt.Web.Core;
using UPCourt.Web.Models;
using UPCourt.Web.Service.BusinessService;
using UPCourt.Web.Service.DataService;

namespace UPCourt.Web.Controllers
{
    public class RegionController : BaseMVCController
    {
        // GET: Region
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanView)]
        public ActionResult Index()
        {
            return View(RegionMvcModel.CopyFromEntityList(RegionDataService.GetLite(db).OrderByDescending(i => i.DisplayOrder), 0));
        }

        // GET: Region/Details/5
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanView)]
        public ActionResult Details(Guid id)
        {
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == id).FirstOrDefault();
            if (dbData == null) { return RedirectToAction("Index"); }
            return View(RegionMvcModel.CopyFromEntity(dbData, 0));
        }

        // GET: Region/Create
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanCreate)]
        public ActionResult Create()
        {
            var model = new RegionMvcModel();
            model.Status = RegionStatus.Active;
            return View(model);
        }

        // POST: Region/Create
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanCreate)]
        [HttpPost]
        public ActionResult Create(RegionMvcModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            if (!CommonForInsertUpdate(model)) { return View(model); }

            Region tempRegion = new Region();
            tempRegion.RegionId = Guid.NewGuid();
            tempRegion.DisplayOrder = MasterBusinessService.GetRegionsDisplayOrder(db);
            InitializeData(tempRegion, model);

            db.Regions.Add(tempRegion);
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, CreatedMessage);
            return RedirectToAction("Create");
        }

        // GET: Region/Edit/5
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanEdit)]
        public ActionResult Edit(Guid id)
        {
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == id).FirstOrDefault();
            if (dbData == null) { return RedirectToAction("Index"); }
            return View(RegionMvcModel.CopyFromEntity(dbData, 0));
        }

        // POST: Region/Edit/5
        [HttpPost]
        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanEdit)]
        public ActionResult Edit(RegionMvcModel model)
        {
            if (!ModelState.IsValid) { return View(model); }
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == model.RegionId).FirstOrDefault();
            if (dbData == null) { return RedirectToAction("Index"); }
            if (!CommonForInsertUpdate(model)) { return View(model); }
            InitializeData(dbData, model);
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, UpdatedMessage);
            return RedirectToAction("Index");
        }
        private void InitializeData(Region tempRegion, RegionMvcModel model)
        {
            tempRegion.Name = model.Name;
            tempRegion.Description = model.Description;
            tempRegion.Status = model.Status;
            tempRegion.IsDefault = model.IsDefault;
            tempRegion.ModifiedBy = AppUser.UserId;
        }
        private bool CommonForInsertUpdate(RegionMvcModel model)
        {
            var nameForCheck = model.Name.TrimX();
            var duplicateCheck = RegionDataService.GetLite(db).FirstOrDefault(i => i.RegionId != model.RegionId && i.Name == nameForCheck);
            if (duplicateCheck != null)
            {
                ModelState.AddModelError(nameof(model.Name), "Region name already exists");
                return false;
            }

            if (model.IsDefault == true)
            {
                var DefaultCheck = RegionDataService.GetLite(db).FirstOrDefault(i => i.RegionId != model.RegionId && i.IsDefault == true);
                if (DefaultCheck != null)
                {
                    ModelState.AddModelError(nameof(model.IsDefault), "Default Region already selected.");
                    return false;
                }
            }

            return true;
        }

        [PageRoleAuthorizarion(PageName.Region, PagePermissionType.CanDelete)]
        public ActionResult Delete(Guid id)
        {
            var dbData = RegionDataService.GetLite(db).Where(i => i.RegionId == id).FirstOrDefault();
            dbData.IsDeleted = true;
            db.SaveChangesWithAudit(Request, AppUser.UserName);
            DisplayMessage(MessageType.Success, DeletedMessage);
            return RedirectToAction("Index");
        }
    }
}

UPCourt.Web/Views/Region/Create.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Add Region";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Region", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.RegionId)
    @Html.AntiForgeryToken()
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Region</h3>
        </div>
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })   <span class="text-danger">*</span>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @maxlength = "75", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @maxlength = "200", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Status, "--Select--", new { @class = "form-control select2", @required = "true", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(c => c.IsDefault, new { @class = "control-label" })
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.IsDefault, new { @class = "form-control " })
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="@Url.Action("Index", "Region")" class="btn btn-primary"> Back </a>
                &nbsp;
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
<!-- /.card -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Details.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Region Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Court Details</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Court Details</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<!-- general form elements -->
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Court</h3>
    </div>
    <form>
        <div class="card-body">
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @type = "text", @readonly = "readonly" } })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @type = "text", @readonly = "readonly" } })

                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                    @Html.EnumDropDownListFor(m => m.Status, "--Select--", new { @class = "form-control select2", @style = "width: 100%", @disabled = "disabled" })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <div class="checkbox">
                        @Html.CheckBoxFor(model => model.IsDefault, new { @disabled = "disabled" })
                        @Html.LabelFor(c => c.IsDefault, new { @class = "col-sm-2 control-label" })
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="@Url.Action("Index", "Region")" class="btn btn-primary">
                Back
            </a>
        </div>

    </form>
</div>
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Edit.cshtml
@model UPCourt.Web.Models.RegionMvcModel

@{
    ViewBag.Title = "Edit Region";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "Region", FormMethod.Post, new { @class = "col-md-12" }))
{
    @Html.HiddenFor(model => model.RegionId)
    @Html.AntiForgeryToken()

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Region</h3>
        </div>
        <form>
            <div class="card-body">
                <div class="row">
                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })    <span class="text-danger">*</span>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Name", @maxlength = "75", @type = "text", @required = "true" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Description", @maxlength = "200", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" }) <br />
                        @Html.EnumDropDownListFor(m => m.Status, "--Select--", new { @class = "form-control select2", @required = "true", @style = "width: 100%" })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-3">
                        @Html.LabelFor(c => c.IsDefault, new { @class = "control-label" })
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.IsDefault, new { @class = "form-control " })
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="@Url.Action("Index", "Region")" class="btn btn-primary"> Back </a>
                &nbsp;
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
}
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/select2/js/CustomSelect.js")
}

UPCourt.Web/Views/Region/Index.cshtml
@model IEnumerable<UPCourt.Web.Models.RegionMvcModel>

@{
    ViewBag.Title = "Region List";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Court</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Court</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title float-right">
                    @Html.ActionLink("Create", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
                </h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <table id="example1" class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Status</th>
                            <th>Default</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="tr-class-2">
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>@item.Status</td>
                                <td>@item.IsDefault</td>
                                <td class="project-actions">
                                    <a class="" title="View" href="@Url.Action("Details", "Region", new { id = item.RegionId })">
                                        <i class="fa fa-eye text-warning fa-iconsize"></i>
                                    </a>
                                    &nbsp;
                                    <a class="" title="Edit" href="@Url.Action("Edit", "Region", new { id = item.RegionId })">
                                        <i class="fa fa-edit text-info fa-iconsize mr-2 "></i>
                                    </a>
                                    &nbsp;
                                    <a title="Delete" onclick="ConfirmDelete('@item.RegionId','@item.Name','Region')">
                                        <i class="fa fa-trash-alt text-danger fa-iconsize mr-2 "></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
@section Scripts {
    @Scripts.Render("~/FrontEnd/plugins/datatables/CustomDataTable.js")
  
}